// The differential corpus.
//
// Generated by combination rather than written out, for the reason the review
// programme keeps rediscovering: a hand-written list is a list somebody has to
// remember to extend, and it decays. Adding an operator or a string function
// here multiplies through every operand set automatically.
//
// Each case is `{ id, category, source, singleValue }`. `source` is a complete
// Lua chunk. `singleValue` says the chunk returns exactly one value, which is
// what mode B needs: `execute_script` returns a bare value for one result and
// an array for several, so a chunk returning two values and a chunk returning
// one array are indistinguishable after the crossing. Multi-return semantics
// are covered in mode A, where nothing has crossed and the ambiguity does not
// arise.

const NUMBERS = [
  '0', '1', '-1', '2', '7', '-7', '10', '100',
  '0.0', '1.0', '-1.0', '0.5', '-0.5', '1.5', '3.25', '1e15', '1e16',
  '0.1', '1/3', '2^53', '2^53+1', '-(2^53)',
  'math.maxinteger', 'math.mininteger', 'math.maxinteger-1', 'math.mininteger+1',
  'math.pi', 'math.huge', '-math.huge', '0/0',
];

const ARITH = ['+', '-', '*', '/', '//', '%', '^'];
const COMPARE = ['==', '~=', '<', '<=', '>', '>='];
const BITWISE = ['&', '|', '~', '<<', '>>'];
const INTS = ['0', '1', '-1', '255', '256', '-256', '65535',
  'math.maxinteger', 'math.mininteger', '2', '63', '64', '-63'];

const STRINGS = [
  '""', '"a"', '"abc"', '"Hello, World"', '"line1\\nline2"', '"tab\\there"',
  '"quote\\"inside"', '"back\\\\slash"', '"\\0embedded"', '"caf\\xC3\\xA9"',
  '"\\xFF\\xFE"', '"  padded  "', '"%d %s"', '"repeat"',
];

const STRING_CALLS = [
  (s) => `#${s}`,
  (s) => `string.upper(${s})`,
  (s) => `string.lower(${s})`,
  (s) => `string.reverse(${s})`,
  (s) => `string.len(${s})`,
  (s) => `string.byte(${s}, 1)`,
  (s) => `string.sub(${s}, 2)`,
  (s) => `string.sub(${s}, 1, 3)`,
  (s) => `string.sub(${s}, -2)`,
  (s) => `string.rep(${s}, 3)`,
  (s) => `string.rep(${s}, 2, "-")`,
  (s) => `string.format("%q", ${s})`,
  (s) => `string.format("%s|", ${s})`,
  (s) => `tostring(${s})`,
  (s) => `tonumber(${s})`,
  (s) => `(${s}):find("a", 1, true)`,
  (s) => `select("#", string.byte(${s}, 1, -1))`,
];

const TABLE_EXPRS = [
  '{}',
  '{1, 2, 3}',
  '{1, 2, 3, nil}',
  '{[1]=1, [2]=2, [4]=4}',
  '{a=1, b=2}',
  '{a=1, 10, 20}',
  '{[1.0]=1}',
  '{[true]=1, [false]=2}',
  '{{1,2},{3,4}}',
  '{n=0}',
  '{["1"]=1, [1]="one"}',
  'setmetatable({}, {__index=function() return 42 end})',
  'setmetatable({}, {__len=function() return 7 end})',
];

// The ipairs walks are capped, and the cap is not defensive padding: one of
// the table expressions below is `setmetatable({}, {__index = function() return
// 42 end})`, over which `ipairs` never terminates — it stops at the first nil
// and `__index` never yields one. Generated corpora produce combinations nobody
// chose, which is their value and also this: the first full run wedged the
// reference process at 100% CPU for ten minutes. A bound here makes a
// non-terminating case a *comparable outcome* on both sides rather than a hang
// on one.
const WALK_CAP = 1000;
const TABLE_OPS = [
  (t) => `#(${t})`,
  (t) => `(function() local c=0 for _ in pairs(${t}) do c=c+1 if c>${WALK_CAP} then return "capped" end end return c end)()`,
  (t) => `(function() local c=0 for _ in ipairs(${t}) do c=c+1 if c>${WALK_CAP} then return "capped" end end return c end)()`,
  (t) => `table.concat((function() local r={} for i,v in ipairs(${t}) do r[i]=tostring(v) if i>${WALK_CAP} then break end end return r end)(), ",")`,
  (t) => `(function() local r = ${t}; return type(r) end)()`,
  (t) => `(function() local r = ${t}; return r end)()`,
  (t) => `(function() local r = ${t}; r[1] = "set"; return r[1] end)()`,
  (t) => `(function() local ok, v = pcall(function() return table.unpack(${t}) end) return ok end)()`,
];

// Expressions whose whole point is that they fail. Error *text* is part of the
// comparison: CR-17's F3 was a wrong error message, and a message is exactly
// the kind of answer that is plausible while being wrong.
const ERROR_EXPRS = [
  'local t = nil; return t.x',
  'local t = nil; t.x = 1',
  'return 1 + {}',
  'return "a" + 1',
  'return "abc" + 1',
  'return #nil',
  'return (nil)()',
  'return (42)()',
  'local t = {}; return t < t',
  'return 1 < "a"',
  'error("plain message")',
  'error("with level", 2)',
  'error({code = 7})',
  'error(nil)',
  'error(setmetatable({}, {__tostring = function() return "custom tostring" end}))',
  'assert(false)',
  'assert(false, "assert message")',
  'assert(nil, 42)',
  'return math.floor("x")',
  'return string.rep("a", -1)',
  'return ("x"):bad()',
  'local a <close> = setmetatable({}, {__close = function() error("close failed") end})',
  'return select(0, 1, 2)',
  'return table.concat({{}})',
  'return tonumber("10", 99)',
];

const COROUTINE_EXPRS = [
  'local co = coroutine.create(function() return 1 end) local ok, v = coroutine.resume(co) return tostring(ok) .. "/" .. tostring(v)',
  'local co = coroutine.create(function() coroutine.yield(1) return 2 end) local _, a = coroutine.resume(co) local _, b = coroutine.resume(co) return tostring(a) .. "/" .. tostring(b)',
  'local co = coroutine.create(function() end) coroutine.resume(co) return coroutine.status(co)',
  'local co = coroutine.create(function() coroutine.yield() end) coroutine.resume(co) return coroutine.status(co)',
  'local co = coroutine.create(function() error("inside") end) local ok, e = coroutine.resume(co) return tostring(ok) .. "/" .. tostring(e)',
  'local f = coroutine.wrap(function() coroutine.yield(1) coroutine.yield(2) end) return f() + f()',
  'local f = coroutine.wrap(function() error("wrapped") end) local ok, e = pcall(f) return tostring(ok) .. "/" .. tostring(e)',
  'return tostring(coroutine.isyieldable())',
  'local co = coroutine.create(function() return coroutine.isyieldable() end) local _, v = coroutine.resume(co) return tostring(v)',
  'local co = coroutine.create(function() coroutine.yield() end) coroutine.resume(co) return tostring(coroutine.close(co))',
  'local co = coroutine.create(function(a, b) return a + b end) local _, v = coroutine.resume(co, 3, 4) return v',
  'local co = coroutine.create(function() local a, b = coroutine.yield(1) return a + b end) coroutine.resume(co) local _, v = coroutine.resume(co, 5, 6) return v',
  'return tostring(coroutine.running())',
  'local co = coroutine.create(function() coroutine.yield(1) end) coroutine.resume(co) coroutine.resume(co) local ok = coroutine.resume(co) return tostring(ok)',
];

const METATABLE_EXPRS = [
  '__add', '__sub', '__mul', '__div', '__mod', '__pow', '__unm', '__idiv',
  '__band', '__bor', '__bxor', '__bnot', '__shl', '__shr',
  '__concat', '__len', '__eq', '__lt', '__le',
];

const MATH_EXPRS = [
  'math.type(1)', 'math.type(1.0)', 'math.type("1")',
  'math.tointeger(3.0)', 'math.tointeger(3.5)', 'math.tointeger("3")',
  'math.floor(-1.5)', 'math.ceil(-1.5)', 'math.floor(1.5)', 'math.ceil(1.5)',
  'math.abs(math.mininteger)', 'math.fmod(7, 3)', 'math.fmod(-7, 3)',
  'math.max(1, 2.0)', 'math.min(1, 2.0)',
  'math.ult(1, -1)', 'tostring(math.maxinteger + 1)',
  'tostring(math.mininteger - 1)', '1 // 0 == nil',
  'tostring(3 // 0.0)', 'tostring(-3 // 0.0)', 'tostring(0/0 ~= 0/0)',
  'string.format("%d", 3.0)', 'tostring(10 // 3)', 'tostring(10.0 // 3)',
  'tostring(2^63)', 'tostring(math.maxinteger // -1)',
  '("%.14g"):format(0.1 + 0.2)', 'tostring(1e308 * 10)',
];

const MISC_EXPRS = [
  'type(nil)', 'type(true)', 'type(1)', 'type("")', 'type({})', 'type(print)',
  'tostring(nil)', 'tostring(true)', 'tostring(1)', 'tostring(1.0)',
  'tonumber("0x10")', 'tonumber("10", 2)', 'tonumber("  12  ")', 'tonumber("1e2")',
  'tonumber("")', 'tonumber("z", 36)', 'tostring(tonumber("inf"))',
  'select("#", 1, 2, 3)', 'select(2, "a", "b", "c")', 'select(-1, "a", "b")',
  'rawequal({}, {})', 'rawlen({1,2,3})', 'rawlen("abcd")',
  'tostring(rawget(setmetatable({}, {__index=function() return 1 end}), "x"))',
  '_VERSION',
  'tostring(next({}))',
  '(function(...) return select("#", ...) end)(nil, nil)',
  'table.concat({1, 2, 3}, "-")',
  'tostring(os.time{year=2000, month=1, day=1, hour=12} ~= nil)',
  'string.pack and "haspack" or "nopack"',
  '#string.pack("i4", 7)',
  'string.unpack("i4", string.pack("i4", 7))',
  'utf8 and utf8.char(233) or "noutf8"',
  'utf8 and utf8.len("caf\\xC3\\xA9") or -1',
  'table.move({1,2,3}, 1, 3, 2, {})[2]',
];

const PATTERN_EXPRS = [
  '("hello world"):match("(%w+) (%w+)")',
  '("hello"):gsub("l", "L")',
  '("a,b,c"):gsub(",", ";")',
  '("abc"):find("b")',
  '("abc"):find("%a+")',
  '("x=1, y=2"):gsub("(%w+)=(%w+)", "%2=%1")',
  '("   trim   "):match("^%s*(.-)%s*$")',
  '(""):match(".*")',
  '("aaa"):gsub("a*", "-")',
  '("abc"):gmatch("%a")()',
  '("2024-01-15"):match("(%d+)-(%d+)-(%d+)")',
  '("%d"):find("%%d")',
  '("[test]"):match("%[(.-)%]")',
  '("abc"):gsub(".", function(c) return c:upper() end)',
  '("one two"):gsub("%w+", {one = "1", two = "2"})',
];

// Combinations whose answer Lua leaves unspecified, so the two sides may
// legitimately differ *and may differ differently on different runs*. A flapping
// case is worse than a missing one: it trains the reader to ignore the report.
//
//   t3/o0 is `#{[1]=1, [2]=2, [4]=4}`. The length operator on a table with a
//   hole may return any border, so 2 and 4 are both correct answers — and this
//   pair genuinely returned 2 on one run and agreed on the next, because the
//   answer depends on the table's internal layout and so on allocation history.
const SKIP_TABLE_CELLS = new Set(['t3/o0']);

function push(cases, category, id, source, singleValue = true) {
  cases.push({ id: `${category}/${id}`, category, source, singleValue });
}

export function buildCorpus() {
  const cases = [];

  // Arithmetic and comparison over every operand pair. This is the bulk of the
  // corpus and the part that would never be written by hand.
  for (const a of NUMBERS) {
    for (const op of ARITH) {
      push(cases, 'arith', `${a}${op}2`, `return tostring(${a} ${op} 2)`);
      push(cases, 'arith', `2${op}${a}`, `return tostring(2 ${op} (${a}))`);
    }
    for (const op of COMPARE) {
      push(cases, 'compare', `${a}${op}2`, `return tostring(${a} ${op} 2)`);
    }
    push(cases, 'number', `identity:${a}`, `return ${a}`);
    push(cases, 'number', `tostring:${a}`, `return tostring(${a})`);
    push(cases, 'number', `mathtype:${a}`, `return math.type(${a})`);
  }

  for (const a of INTS) {
    for (const op of BITWISE) {
      push(cases, 'bitwise', `${a}${op}3`, `return tostring((${a}) ${op} 3)`);
    }
    push(cases, 'bitwise', `bnot:${a}`, `return tostring(~(${a}))`);
  }

  for (let si = 0; si < STRINGS.length; si++) {
    const s = STRINGS[si];
    for (let ci = 0; ci < STRING_CALLS.length; ci++) {
      push(cases, 'string', `s${si}/c${ci}`, `return tostring(${STRING_CALLS[ci](s)})`);
    }
    push(cases, 'string', `identity:s${si}`, `return ${s}`);
    push(cases, 'string', `concat:s${si}`, `return ${s} .. "|end"`);
  }

  for (let ti = 0; ti < TABLE_EXPRS.length; ti++) {
    const t = TABLE_EXPRS[ti];
    for (let oi = 0; oi < TABLE_OPS.length; oi++) {
      if (SKIP_TABLE_CELLS.has(`t${ti}/o${oi}`)) continue;
      push(cases, 'table', `t${ti}/o${oi}`, `return ${TABLE_OPS[oi](t)}`);
    }
  }

  for (let i = 0; i < ERROR_EXPRS.length; i++) {
    // Run bare, so the error is the outcome the canonical form reports.
    push(cases, 'error', `e${i}`, ERROR_EXPRS[i]);
    // And through pcall, so the *message* is a value that can be compared even
    // where the two sides' error plumbing differs.
    push(cases, 'error-message', `e${i}`,
      `local ok, err = pcall(function() ${ERROR_EXPRS[i]} end) return tostring(ok) .. "|" .. tostring(err)`);
  }

  for (let i = 0; i < COROUTINE_EXPRS.length; i++) {
    push(cases, 'coroutine', `c${i}`, COROUTINE_EXPRS[i]);
  }

  for (const mm of METATABLE_EXPRS) {
    const unary = ['__unm', '__bnot', '__len'].includes(mm);
    const body = unary
      ? `local mt = { ${mm} = function(a) return "${mm}" end }
         local t = setmetatable({}, mt)
         local ok, v = pcall(function() return ${mm === '__unm' ? '-t' : mm === '__bnot' ? '~t' : '#t'} end)
         return tostring(ok) .. "|" .. tostring(v)`
      : `local mt = { ${mm} = function(a, b) return "${mm}" end }
         local t = setmetatable({}, mt)
         local ok, v = pcall(function() return t ${opFor(mm)} t end)
         return tostring(ok) .. "|" .. tostring(v)`;
    push(cases, 'metatable', mm, body);
  }

  for (let i = 0; i < MATH_EXPRS.length; i++) {
    push(cases, 'math', `m${i}`, `local ok, v = pcall(function() return ${MATH_EXPRS[i]} end) return tostring(ok) .. "|" .. tostring(v)`);
  }
  for (let i = 0; i < MISC_EXPRS.length; i++) {
    push(cases, 'misc', `m${i}`, `local ok, v = pcall(function() return ${MISC_EXPRS[i]} end) return tostring(ok) .. "|" .. tostring(v)`);
  }
  for (let i = 0; i < PATTERN_EXPRS.length; i++) {
    push(cases, 'pattern', `p${i}`, `local ok, v = pcall(function() return ${PATTERN_EXPRS[i]} end) return tostring(ok) .. "|" .. tostring(v)`);
  }

  // Values returned *as values*, not stringified: this is the column mode B
  // exists for. Everything above compares a string the Lua side built; these
  // compare what actually crossed the boundary.
  const CROSSING = [
    '0', '1', '-1', '3.5', '-0.0', '1/0', '-1/0', '0/0',
    'math.maxinteger', 'math.mininteger', '2^53', '2^53+1', '2^53-1',
    '9007199254740993', '-9007199254740993',
    '1e15', '1e16', '0.1', '1/3', 'math.pi',
    'true', 'false', 'nil',
    '""', '"abc"', '"caf\\xC3\\xA9"', '"\\0mid"', '"\\xFF"', '"line\\nbreak"',
    '{}', '{1,2,3}', '{a=1}', '{a=1,b="two",c=true}', '{{1},{2}}',
    '{[1]=1,[3]=3}', '{1,nil,3}', '{n=1,[1]=10}',
    'string.rep("x", 100)',
    '{1.0, 2.0}', '{[1]="a", [2]="b", x="c"}',
  ];
  for (let i = 0; i < CROSSING.length; i++) {
    push(cases, 'crossing', `v${i}:${CROSSING[i].slice(0, 24)}`, `return ${CROSSING[i]}`);
  }

  return cases;
}

function opFor(mm) {
  return {
    __add: '+', __sub: '-', __mul: '*', __div: '/', __mod: '%', __pow: '^',
    __idiv: '//', __band: '&', __bor: '|', __bxor: '~', __shl: '<<', __shr: '>>',
    __concat: '..', __eq: '==', __lt: '<', __le: '<=',
  }[mm];
}
